name: Build

# on:
#   push:
#     branches: [ main ]
#   workflow_dispatch:

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Validate tag format
        run: |
          if [[ ! ${{ github.ref_name }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$ ]]; then
            echo "Invalid tag format. Use: v0.0.1 or v0.0.1-beta"
            exit 1
          fi
  build:
    needs: validate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history
          token: ${{ secrets.GITHUB_TOKEN }} # Explicitly set token for push permissions
          ref: main # Explicitly checkout main branch

      # Install build dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      # Build mklittlefs
      - name: Build mklittlefs
        run: |
          git clone --recursive https://github.com/earlephilhower/mklittlefs.git
          cd mklittlefs
          make dist
          sudo cp mklittlefs /usr/local/bin/
          cd ..
          mklittlefs --help
      
      # Create ei_config
      - name: Create dummy ei_config.json
        run: |
          cp data/ei_config.template.json data/ei_config.json
      
      # Make firmware and other build dir
      - name: Make build directory
        run: |
          rm -rf build
          mkdir -p build

      # Create LittleFS binary
      - name: Create LittleFS binary for XIAO ESP32-S3
        run: |
          mklittlefs -c data -p 256 -b 4096 -s 1572864 build/filesystem.littlefs.xiaoesp32s3.bin
          mklittlefs -l -d 5 build/filesystem.littlefs.xiaoesp32s3.bin
      
      - name: Create LittleFS binary for AI Thinker ESP32-CAM
        run: |
          mklittlefs -c data -p 256 -b 4096 -s 917504 build/filesystem.littlefs.aithinkercam.bin
          mklittlefs -l -d 5 build/filesystem.littlefs.aithinkercam.bin
      
      - name: Create LittleFS binary for ESP_EYE
        run: |
          mklittlefs -c data -p 256 -b 4096 -s 917504 build/filesystem.littlefs.espeye.bin
          mklittlefs -l -d 5 build/filesystem.littlefs.espeye.bin

      - name: Install Arduino CLI
        run: |
          mkdir -p "$HOME/arduino-cli"
          cd "$HOME/arduino-cli"
          until curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR="$HOME/arduino-cli" sh; do
            echo "Retrying installation of Arduino CLI..."
            sleep 5
          done
          export PATH="$HOME/arduino-cli:$PATH"
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
        shell: bash

      - name: Install Libraries
        run: |
          export PATH="$HOME/arduino-cli:$PATH"
          mkdir -p "$HOME/Arduino/libraries"
          cd "$HOME/Arduino/libraries"
          git clone https://github.com/ESP32Async/AsyncTCP.git
          git clone https://github.com/ESP32Async/ESPAsyncWebServer.git
          cd "$HOME"
          ls -l
          arduino-cli lib install ArduinoJson

      - name: Add build info in build directory
        run: |
          echo "Build started at: $(date)" > build/build_info.txt
          echo "Git commit: ${{ github.sha }}" >> build/build_info.txt
          echo "Version: ${{ github.ref_name }}" >> build/build_info.txt
      
      - name: Update Camera Model Configuration to CAMERA_MODEL_XIAO_ESP32S3
        run: |
          # Uncomment CAMERA_MODEL_XIAO_ESP32S3 if it's commented out
          sed -i 's|// #define CAMERA_MODEL_XIAO_ESP32S3 1|#define CAMERA_MODEL_XIAO_ESP32S3 1|g' config.h
          # Comment out CAMERA_MODEL_AI_THINKER if it's uncommented
          sed -i 's|^#define CAMERA_MODEL_AI_THINKER 1|// #define CAMERA_MODEL_AI_THINKER 1|g' config.h
          # Comment out CAMERA_MODEL_ESP_EYE if it's uncommented
          sed -i 's|^#define CAMERA_MODEL_ESP_EYE 1|// #define CAMERA_MODEL_ESP_EYE 1|g' config.h
          # Verify the changes
          echo "Updated config.h contents:"
          cat config.h

      - name: Compile Sketch for CAMERA_MODEL_XIAO_ESP32S3
        run: |
          export PATH="$HOME/arduino-cli:$PATH"
          arduino-cli compile \
          --fqbn "esp32:esp32:XIAO_ESP32S3:USBMode=hwcdc,CDCOnBoot=default,MSCOnBoot=default,DFUOnBoot=default,UploadMode=default,CPUFreq=240,FlashMode=dio,FlashSize=8M,PartitionScheme=default_8MB,DebugLevel=none,PSRAM=opi,LoopCore=1,EventsCore=1,EraseFlash=none,UploadSpeed=921600,JTAGAdapter=default" \
          --output-dir build . 2>&1 | tee build/build_log.txt

      - name: Verify binary files
        run: |
          cd build
          for file in "EI_ESP32_CAM_SERVER.ino.bin" "EI_ESP32_CAM_SERVER.ino.merged.bin"; do
            if [ ! -f "$file" ]; then
              echo "ERROR: Required file $file not found!"
              exit 1
            fi
          done
          ls -la
          cd ..

      - name: Rename binary files with xaioesp32s3 suffix
        run: |
          cd build
          for f in *.ino.*; do 
            if [ -f "$f" ]; then
              newname="${f/.ino./.xiaoesp32s3.}"
              mv "$f" "$newname"
              echo "Renamed: $f → $newname"
            fi
          done
          cp EI_ESP32_CAM_SERVER.xiaoesp32s3.merged.bin "EI_ESP32_CAM_SERVER.xiaoesp32s3.merged_${GITHUB_REF_NAME}.bin"
          echo "Created a copy of the binary with version: ${GITHUB_REF_NAME}"
          cp filesystem.littlefs.xiaoesp32s3.bin "filesystem.littlefs.xiaoesp32s3_${GITHUB_REF_NAME}.bin"
          echo "Created a copy of the LittleFS file sys binary with version: ${GITHUB_REF_NAME}"
          ls -la
          cd ..
      
      - name: Update Camera Model Configuration to CAMERA_MODEL_AI_THINKER
        run: |
          # Uncomment CAMERA_MODEL_AI_THINKER if it's commented out
          sed -i 's|// #define CAMERA_MODEL_AI_THINKER 1|#define CAMERA_MODEL_AI_THINKER 1|g' config.h
          # Comment out CAMERA_MODEL_XIAO_ESP32S3 if it's uncommented
          sed -i 's|^#define CAMERA_MODEL_XIAO_ESP32S3 1|// #define CAMERA_MODEL_XIAO_ESP32S3 1|g' config.h
          # Comment out CAMERA_MODEL_ESP_EYE if it's uncommented
          sed -i 's|^#define CAMERA_MODEL_ESP_EYE 1|// #define CAMERA_MODEL_ESP_EYE 1|g' config.h
          # Verify the changes
          echo "Updated config.h contents:"
          cat config.h
    
      - name: Compile Sketch for CAMERA_MODEL_AI_THINKER
        run: |
          export PATH="$HOME/arduino-cli:$PATH"
          arduino-cli compile \
          --fqbn "esp32:esp32:esp32:CPUFreq=240,FlashMode=dio,FlashFreq=80,FlashSize=4M,PartitionScheme=huge_app,PSRAM=enabled,DebugLevel=none,LoopCore=1,EventsCore=1,EraseFlash=none,JTAGAdapter=default,ZigbeeMode=default,UploadSpeed=460800" \
          --output-dir build . 2>&1 | tee build/build_log.txt

      - name: Verify binary files
        run: |
          cd build
          for file in "EI_ESP32_CAM_SERVER.ino.bin" "EI_ESP32_CAM_SERVER.ino.merged.bin"; do
            if [ ! -f "$file" ]; then
              echo "ERROR: Required file $file not found!"
              exit 1
            fi
          done
          ls -la
          cd ..

      - name: Rename binary files with aithinkercam suffix
        run: |
          cd build
          for f in *.ino.*; do 
            if [ -f "$f" ]; then
              newname="${f/.ino./.aithinkercam.}"
              mv "$f" "$newname"
              echo "Renamed: $f → $newname"
            fi
          done
          cp EI_ESP32_CAM_SERVER.aithinkercam.merged.bin "EI_ESP32_CAM_SERVER.aithinkercam.merged_${GITHUB_REF_NAME}.bin"
          echo "Created a copy of the binary with version: ${GITHUB_REF_NAME}"
          cp filesystem.littlefs.aithinkercam.bin "filesystem.littlefs.aithinkercam_${GITHUB_REF_NAME}.bin"
          echo "Created a copy of the LittleFS file sys binary with version: ${GITHUB_REF_NAME}"
          ls -la
          cd ..
      
      - name: Update Camera Model Configuration to CAMERA_MODEL_ESP_EYE
        run: |
          # Comment out CAMERA_MODEL_XIAO_ESP32S3 if it's uncommented
          sed -i 's|^#define CAMERA_MODEL_XIAO_ESP32S3 1|// #define CAMERA_MODEL_XIAO_ESP32S3 1|g' config.h
          # Comment out CAMERA_MODEL_AI_THINKER if it's uncommented
          sed -i 's|^#define CAMERA_MODEL_AI_THINKER 1|// #define CAMERA_MODEL_AI_THINKER 1|g' config.h
          # Uncomment CAMERA_MODEL_ESP_EYE if it's commented out
          sed -i 's|// #define CAMERA_MODEL_ESP_EYE 1|#define CAMERA_MODEL_ESP_EYE 1|g' config.h
          # Verify the changes
          echo "Updated config.h contents:"
          cat config.h
      
      - name: Compile Sketch for CAMERA_MODEL_ESP_EYE
        run: |
          export PATH="$HOME/arduino-cli:$PATH"
          arduino-cli compile \
          --fqbn "esp32:esp32:esp32wrover:FlashMode=dio,FlashFreq=80,PartitionScheme=huge_app,DebugLevel=none,EraseFlash=none,UploadSpeed=921600" \
          --output-dir build . 2>&1 | tee build/build_log.txt
      
      - name: Verify binary files
        run: |
          cd build
          for file in "EI_ESP32_CAM_SERVER.ino.bin" "EI_ESP32_CAM_SERVER.ino.merged.bin"; do
            if [ ! -f "$file" ]; then
              echo "ERROR: Required file $file not found!"
              exit 1
            fi
          done
          ls -la
          cd ..
      
      - name: Rename binary files with espeye suffix
        run: |
          cd build
          for f in *.ino.*; do 
            if [ -f "$f" ]; then
              newname="${f/.ino./.espeye.}"
              mv "$f" "$newname"
              echo "Renamed: $f → $newname"
            fi
          done
          cp EI_ESP32_CAM_SERVER.espeye.merged.bin "EI_ESP32_CAM_SERVER.espeye.merged_${GITHUB_REF_NAME}.bin"
          echo "Created a copy of the binary with version: ${GITHUB_REF_NAME}"
          cp filesystem.littlefs.espeye.bin "filesystem.littlefs.espeye_${GITHUB_REF_NAME}.bin"
          echo "Created a copy of the LittleFS file sys binary with version: ${GITHUB_REF_NAME}"
          ls -la
          cd ..

      - name: Commit and push binary files in the repository too
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git fetch origin
          git checkout main
          # Debug: Print current directory and files
          pwd
          ls -la
          # Force add all files in binary directory
          git add -f build/
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          # Debug: Show what's being committed
          git status
          git commit -m "Add compiled firmware binaries for version ${GITHUB_REF_NAME}"
          git push origin main || exit 1
          # Handle tag operations with error catching
          git push all :refs/tags/${GITHUB_REF_NAME} || echo "Warning: Failed to delete tag from some remotes - continuing..."
          git tag -d ${GITHUB_REF_NAME} || echo "Warning: Failed to delete local tag - continuing..."
          git tag ${GITHUB_REF_NAME}
          git push all ${GITHUB_REF_NAME} || echo "Warning: Failed to push tag to some remotes - continuing..."

      - name: Create firmware ZIP
        run: |
          zip -r firmwares.zip build/*
          ls -la
          pwd

      - name: Generate Release Notes
        run: |
          {
            echo "## XIAO ESP32-S3 Firmware Release ${{ github.ref_name }}"
            echo "### Build Information"
            echo "- Build Date: $(date)"
            echo "- Commit: ${{ github.sha }}"
            echo "- Builder: ${{ github.actor }}"
            echo ""
            echo "### All compiled firmware binaries and other files"
            echo "- firmwares.zip contains:"
            cd build
            for file in *.*; do
              if [ "$file" != "build_log.txt" ]; then
                size=$(ls -l "$file" | awk '{print $5}')
                echo "  - $file ($size bytes)"
              fi
            done
            cd ..
            echo "### Main firmware binaries"
            echo "- build/EI_ESP32_CAM_SERVER.xiaoesp32s3.merged.bin"
            echo "- build/EI_ESP32_CAM_SERVER.aithinkercam.merged.bin"
            echo "- build/EI_ESP32_CAM_SERVER.espeye.merged.bin"
            echo ""
            echo "### LittleFS FileSys binaries"
            echo "- build/filesystem.littlefs.xiaoesp32s3.bin"
            echo "- build/filesystem.littlefs.aithinkercam.bin"
            echo "- build/filesystem.littlefs.espeye.bin"
            echo ""
          } > release_notes.md
          pwd
          ls -la
          cat release_notes.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            firmwares.zip
            build/EI_ESP32_CAM_SERVER.xiaoesp32s3.merged_${{ github.ref_name }}.bin
            build/filesystem.littlefs.xiaoesp32s3_${{ github.ref_name }}.bin
            build/EI_ESP32_CAM_SERVER.aithinkercam.merged_${{ github.ref_name }}.bin
            build/filesystem.littlefs.aithinkercam_${{ github.ref_name }}.bin
            build/EI_ESP32_CAM_SERVER.espeye.merged_${{ github.ref_name }}.bin
            build/filesystem.littlefs.espeye_${{ github.ref_name }}.bin
          body_path: release_notes.md
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
