name: Arduino CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Arduino CLI
      run: |
        mkdir -p "$HOME/arduino-cli"
        cd "$HOME/arduino-cli"
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR="$HOME/arduino-cli" sh
        export PATH="$HOME/arduino-cli:$PATH"
        arduino-cli config init
        arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        arduino-cli core update-index
        arduino-cli core install esp32:esp32
    
    - name: Install Libraries
      run: |
        export PATH="$HOME/arduino-cli:$PATH"
        mkdir -p "$HOME/Arduino/libraries"
        cd "$HOME/Arduino/libraries"
        git clone https://github.com/ESP32Async/AsyncTCP.git
        git clone https://github.com/ESP32Async/ESPAsyncWebServer.git

    - name: Create credentials file for CI
      run: |
        echo '#ifndef CREDENTIALS_H' > credentials.h
        echo '#define CREDENTIALS_H' >> credentials.h
        echo 'const char* ssid = "TEST_SSID";' >> credentials.h
        echo 'const char* password = "TEST_PASSWORD";' >> credentials.h
        echo '#endif' >> credentials.h
    
    - name: Compile Sketch
      run: |
        export PATH="$HOME/arduino-cli:$PATH"
        arduino-cli compile --fqbn "esp32:esp32:XIAO_ESP32S3:USBMode=hwcdc,CDCOnBoot=default,MSCOnBoot=default,DFUOnBoot=default,UploadMode=default,CPUFreq=240,FlashMode=qio,FlashSize=8M,PartitionScheme=default_8MB,DebugLevel=none,PSRAM=opi,LoopCore=1,EventsCore=1,UploadSpeed=921600,JTAGAdapter=default" . -v